# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uMJXuRHRYItqW4vySW0Mtu_C3bPNCl4P
"""

# This is my week-2 Session 4 practice

# Activity-1
list1 = ['physics', 'chemistry', 1997, 2000]
list1[3]

list1 = ['physics', 'chemistry', 1997, 2000]
list1[0]

list1 = ['physics', 'chemistry', 1997, 2000]
list1[4]





m = [2]
y = [4]
x = m + y
x

list1 = ['aih']
len(list1)

list1 = []
len(list1)

list1 = ['aih']
len(list1)

list1 = list()
len(list1)

list1 = list()
list1.append(1997)
len(list1)

list1 = []
list1[0] = 2

list1 = [4, 6]
list1[0] = 8
list1

m = [ 2, 4, 5]
2 in m

m = [ 2, 4, 5]
6 in m

m = [3, 6, 9]
m[0]

m = [ 2, 4, 5]
m[-1]

m = [ 2, 4, 5]
m[0]

m = [ 2, 4, 5, 6, 7]
m[1:4]
m[1:]

m = [1, 3, 7, 2, 8, 10]
m[1:-2]

m = [1, 3, 7, 2, 8, 10]
m.append(3)
m

m = [1, 3, 7, 2, 8, 10, 3]
m.index(3)

m = [1, 3, 7, 2, 8, 10, 3]
m.index(13)



m = [1, 3, 7, 2, 8, 10, 3]
7 in m

m = [1, 3, 7, 2, 8, 10, 3]
13 in m

m = [1, 3, 7, 2, 8, 10, 3]
13 not in m



m = [1, 3, 7, 2, 8, 10, 3]
m.sort()
m

m = [1, 3, 7, 2, 8, 10, 3]
m.sort(reverse=True)
m

m = [1, 3, 7, 2, 8, 10]
m.reverse()
m

m =[10, 8, 15, 2, 7, 3, 1, 2]
del m[2]
m

m = [10, 8, 2, 7, 3, 1, 2]
m.remove(7)
m

m = [10, 8, 2, 3, 1, 2]
max(m)

m = [10, 8, 2, 3, 1, 2]
min(m)

m = [10, 8, 2, 3, 1, 2]
n=[]
n = n + m
n

m = [10, 8, 2, 3, 1, 2]
n=[]
n = n + m
n is m

m = [10, 8, 2, 3, 1, 2]
n = m
n is m

students = [
["sam", 85.5, "hd"],
["ann", 67, "cr"]
]
students[0]

students = [
["sam", 85.5, "hd"],
["ann", 67, "cr"]
]
students[0][0]

students = [
["sam", 85.5, "hd"],
["ann", 67, "cr"]
]
for astudent in students:
    print(astudent)

num = [1, 2, 3, 4, 5]
max_num = max(num)
min_num = min(num)
print(max_num,'\n',min_num)